name: Sample Action
run-name: sample
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checkout ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls ${{ github.workspace }}
