name: Sample Action

on: [push]

jobs:
  sample_job:
    name: Sample Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "checkout ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls ${{ github.workspace }}
